language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -e .
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  username: __token__
  password:
    secure: NQr45wfsTqM+SCmwJ0tj7aQvyTY1B8sIl7T7JeAiHaWS+XgwXsqachkzZiRVkxJJ/VruknbXsSWHYMU4vFqZGj6SlW7qNg6N8vkz1OKBD7gODhDZQY25IuPnwLIC/PHjfMl4WnBSBODU6NMsmLb29tSW9+ty8IWiwkSvHsiXxvSrgvFgAsRD2daIdtQu72klJ85bdMDTs/KYcUpfBW+S/1r4BQjbyBE++URLszyfnFFq7RNm8xZIClo8Fshe2lKgW3AdzDCTDnlWh3nsASWWEyyClpzFDJ8i4aIRFaydDCJNYaJURZO5X5kdD7Ifb/97xt/m+6VCGLB+iILgf48Bczbs8bZ/PEdkkIKc64wGkIhNYNzwHZ8/mR6x3NfX4TN8dtSrbakKslWbrGlA1te8tPwPogjJQhrXXmwVDLhwIAMjIa1Cmc0doKLehRd4c5EdhK+iR5uwFb80LAaG1t9l7F1RIU3rO4zKDKvPuFJQQhTlPdjD3/Z9di4LInB6egrn7dSyNUj7YjZ7Ix5/9RajbJ+1GX3tcbDzui+MEGjrEpE1A11hOc+tkJZlbe5iW00XThZtqt3h4VRoG5bCH/I9yNSh/sjCud7AO7b5OnEmQdGuajbmDKn7OxAOqpW9AgaMpF4OZ3tNmPiTNHHpjrUOe7SlJWqTkz0NH2iAi1BrL9Q=
  on:
    tags: true
    python: 3.9
