# Site settings
title: FIRE Studio
email: alex.b.gurvich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/firestudio" # the subpath of your site, e.g. /blog/
url: "alexbgurvi.ch" # the base hostname & protocol for your site

# User setting
owner: Alex Gurvich
email: alex.b.gurvich@gmail.com
facebook_username:
twitter_username: alexbgurvich
github_username: agurvich
copyright: Alex Gurvich


# Build settings
markdown: kramdown
